### PR TITLE
Fix automatic unredirect reenabling (port from aunetx fork)

### LINKED ISSUE #17: Extension stops working after some time
After gnome has been running for some time, the extension stops working, requiring to disable and enable it again to make it work again.

### PR DESCRIPTION
**Pull request by yjhn**
Fixes #17.

### CODE REVIEW

**Review by cj-kazimieras-vaina — APPROVED** [review]
Interesting... something is not yet initialized when the extension is started.

**Comment by yjhn** [comment]
I didn't test it :( (currently running GNOME 42, so incompatible). So testing and fixes are appreciated.

**Comment by ryanmusante** [comment]
I'll test it. But what is a finite way of showing that unredirect is enabled or not?

**Comment by yjhn** [comment]
At least for me (Pop_OS 22.04, X11, Intel iGPU), full screen videos played with mpv player (https://github.com/mpv-player/mpv) don't tear with unredirect disabled.

**Comment by yjhn** [comment]
The issue is already fixed in a different way, so this is no longer relevant.

**Pull request closed without merging**
